# Generated by Django 4.2.2 on 2023-06-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_capacity_alter_room_created_at_and_more'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.resident'),
        ),
        migrations.AlterField(
            model_name='book',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
